import {
  Loader2,
  LayoutDashboard,
  Users,
  FileText,
  AlertTriangle,
  Bell,
  Building,
  File,
  LogOut,
  Settings,
  Menu,
  X,
  Plus,
  Trash,
  Edit,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Search,
  Check,
  Download,
  Upload,
  User,
  Shield,
  CreditCard,
  PieChart,
  Activity,
  Calendar,
  Filter,
  ArrowRight,
  ArrowLeft,
  Moon,
  Sun,
  MoreVertical,
  MoreHorizontal,
  Mail,
  Phone,
  MapPin,
  Lock,
  Eye,
  EyeOff,
  RefreshCw,
  Send,
  MessageSquare,
  Bot,
} from "lucide-react";

export const Icons = {
  spinner: Loader2,
  dashboard: LayoutDashboard,
  users: Users,
  claims: FileText,
  appeals: Shield,
  denials: AlertTriangle,
  notifications: Bell,
  organizations: Building,
  files: File,
  settings: Settings,
  logout: LogOut,
  menu: Menu,
  close: X,
  add: Plus,
  delete: Trash,
  edit: Edit,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  search: Search,
  check: Check,
  download: Download,
  upload: Upload,
  user: User,
  billing: CreditCard,
  analytics: PieChart,
  activity: Activity,
  calendar: Calendar,
  filter: Filter,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  sun: Sun,
  moon: Moon,
  moreVertical: MoreVertical,
  moreHorizontal: MoreHorizontal,
  mail: Mail,
  phone: Phone,
  location: MapPin,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  refresh: RefreshCw,
  send: Send,
  chat: MessageSquare,
  bot: Bot,
};
